version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80" # Expose the frontend on port 3000 (container port 80)

  backend:
    build:
      context: ./backend
    ports:
      - "5000:80" # Expose the backend on port 5000 (container port 80)
    depends_on:
      - frontend
    env_file:
      - ./backend/.env.local