services:
  frontend:
    image: frontend-image
    build:
      context: ./frontend
    ports:
      - "3000:80" # Expose the frontend on port 3000 (container port 80)

  backend:
    image: backend-image
    build:
      context: ./backend
    ports:
      - "5000:80" # Expose the backend on port 5000 (container port 80)
    depends_on:
      - frontend
    env_file:
      - ./backend/.env.local
